In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"E:\AI\LibrariesForAI\Supervised_Learning\1_Simple_Linear_regression\homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
x_df = df.drop(['price'],axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [4]:
y_df=df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [5]:
# create linear reg object
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [6]:
lr.coef_

array([135.78767123])

In [7]:
lr.intercept_

180616.43835616432

#### Pickle File

In [8]:
import pickle

In [11]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)


In [12]:
with open("lr_model",'rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.predict([[5000]])

array([859554.79452055])

In [16]:
### create a file named sample.json with some data:
import json

sampleJson = {
    "name": "Luminar",
    "place": "Kochi",
    "phonenumber":"8714135828"
}

json_object = json.dumps(sampleJson)

In [18]:
with open("sample.json","w") as file:
    file.write(json_object)

In [20]:
with open("sample.json","r") as file:
    newdata = json.load(file)

In [21]:
newdata

{'name': 'Luminar', 'place': 'Kochi', 'phonenumber': '8714135828'}

#### Save trained model using Joblib

In [23]:
import joblib 

In [24]:
joblib.dump(lr,'model_joblib_new')

['model_joblib_new']

In [27]:
mj = joblib.load('model_joblib_new')

In [28]:
mj.coef_

array([135.78767123])

In [29]:
mj.intercept_

180616.43835616432

In [26]:
joblib.load('lr_model')

LinearRegression()