In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
lr = LinearRegression()
lr.fit(df[['area']],df.price)

LinearRegression()

In [5]:
lr.coef_

array([135.78767123])

In [6]:
lr.intercept_

180616.43835616432

In [8]:
lr.predict([[5000]])

array([859554.79452055])

#### Save Model To a File Using Python Pickle

In [9]:
import pickle

In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(lr,file)

#### Load Saved Model

In [13]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [14]:
mp.coef_

array([135.78767123])

In [15]:
mp.intercept_

180616.43835616432

In [16]:
mp.predict([[5000]])

array([859554.79452055])

#### Save Trained Model Using joblib

In [20]:
import joblib

In [21]:
joblib.dump(lr, 'model_joblib')

['model_joblib']

#### Load Saved Model

In [22]:
mj = joblib.load('model_joblib')

In [23]:
mj.coef_

array([135.78767123])

In [24]:
mj.intercept_

180616.43835616432

In [25]:
mj.predict([[5000]])

array([859554.79452055])